# Generated by Django 4.1 on 2022-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("review", models.TextField()),
                ("watched", models.TextField()),
                ("rating", models.IntegerField()),
                ("release_date", models.DateField()),
            ],
        ),
    ]
